
export enum View {
  HOME = 'HOME',
  ASSISTANT = 'ASSISTANT',
  TASKS = 'TASKS',
  CALENDAR = 'CALENDAR',
  NOTES = 'NOTES',
  MARKET = 'MARKET', // Keeping for internal usage if needed
  SETTINGS = 'SETTINGS'
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  status: 'todo' | 'in-progress' | 'done';
  priority: 'low' | 'medium' | 'high';
}

export interface CalendarEvent {
  id: string;
  title: string;
  date: string; // ISO String
  description?: string;
  priority?: 'low' | 'medium' | 'high';
}

export interface NoteAttachment {
  name: string;
  type: string;
  data: string; // Base64 string
}

export interface Note {
  id: string;
  title: string;
  content: string;
  date: string; // ISO String
  attachments?: NoteAttachment[];
}

export interface GeneratedFile {
  name: string;
  type: string; // mime type
  data: string; // text content
}

export interface SystemElement {
  id: string;
  title: string;
  type: 'page' | 'database' | 'dashboard' | 'automation';
  description?: string;
  children?: SystemElement[];
  properties?: string[];
  views?: string[];
}

export interface SystemStructure {
  title: string;
  elements: SystemElement[];
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  content: string;
  timestamp: Date;
  attachmentName?: string;
  isThinking?: boolean;
  groundingMetadata?: any; // Stores search results/sources
  image?: string; // Base64 string of generated image
  generatedFile?: GeneratedFile; // File generated by the model
  systemStructure?: SystemStructure;
}

export interface ChatSession {
  id: string;
  title: string;
  messages: ChatMessage[];
  updatedAt: Date;
}

export interface MarketDataPoint {
  month: string;
  revenue: number;
  expenses: number;
  profit: number;
}

export interface MarketBriefing {
  sector: string;
  content: string;
  lastUpdated: string; // ISO Date string YYYY-MM-DD
}

export interface ToastMessage {
  id: string;
  type: 'success' | 'error' | 'info';
  message: string;
}
